### ISSUE TITLE
ValueError: Cannot register model architecture for unknown model type (sat_transformer)

### ISSUE THREAD

**Issue by ustcdane** [yongchanghao/multi-task-nat#1]
Hi,   when  run  sh run/train.sh  failed,
 error info:

    import fairseq.models  # noqa
  File "/xx/multi-task-nat/fairseq/models/__init__.py", line 128, in <module>
    module = importlib.import_module('fairseq.models.' + model_name)
  File "/root/anaconda3/envs/xxx/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/xx/multi-task-nat/fairseq/models/mt_transformer.py", line 215, in <module>
    @register_model_architecture("sat_transformer", "sat_transformer")
  File "/xx/multi-task-nat/fairseq/models/__init__.py", line 109, in register_model_arch_fn
    raise ValueError('Cannot register model architecture for unknown model type ({})'.format(model_name))
ValueError: Cannot register model architecture for unknown model type (sat_transformer)

**Comment by ustcdane** [comment]
I think should modify this function https://github.com/yongchanghao/multi-task-nat/blob/955060b6fb68346681fc26251c3e9f437294de9b/fairseq/models/mt_transformer.py#L216

### modify   fairseq/models/mt_transformer.py

`#@register_model_architecture("sat_transformer",` "sat_transformer")
`@register_model_architecture("mt_transformer",` "mt_transformer")
`def` base_architecture(args):
    args.encoder_embed_path = getattr(args, "encoder_embed_path", None)
    args.encoder_embed_dim = getattr(args, "encoder_embed_dim", 512)
    ...

#### add 
`@register_model_architecture("mt_transformer", "mt_sat_transformer")
`def sat_architecture(args):
   base_architecture(args)


###  modify run/train.sh 

 --arch **mt_sat_transformer** \

**Comment by yongchanghao** [comment]
Hi @ustcdane. Yes you are right! This seems a renaming problem when publishing our code. I will update this rencently. Thank you!
